### ISSUE TITLE
Image samples

### ISSUE THREAD

**Issue by amreniouinnovent** [DrAchernar/location-based-AR-app#1]
I wonder if you could add sample images of the app in your README.md file?
Thanks

**Comment by DrAchernar** [comment]
It doesn't matter cause I applied this project for my faculty entry in campus. Change images under
 - **/iOS/Runner/firatcard.png** (its your image or object to use after detected target object on camera)
- **/ios/Runner/Assets.xcassets/AR Resources.arresourcegroup/earth2.arreferenceimage/earth2.jpg** is the target image that you want to detect. So on my project, it was my faculty entry photo. You can change or add on Xcode Assets.xcassets. You can add AR Resource groups and images that different names or category. 

I didn't add these cause there are all of them in [Flutter ARKit plugin usage examples](https://github.com/olexale/arkit_flutter_plugin/tree/master/example).
